### ISSUE TITLE
Tests fail on fresh clone and install

### ISSUE THREAD

**Issue by kumavis** [ExpoSEJS/ExpoSE#100]
steps
1. git clone + cd
2. npm install
3. npm test

test output here https://gist.github.com/kumavis/53d1f802fa8109790d343835d9ef6eb0

I'll take a closer look at the CI to try and figure out what I'm missing

**Comment by xv-blakel** [comment]
It's likely the NPM version, ExpoSE currently doesn't work with recent versions of Node.js. EXPOSE_PRINT_PATHS=1 set as an env variable should highlight what is actually failing under the hood

**Comment by kumavis** [comment]
using [`ndb`](https://github.com/GoogleChromeLabs/ndb) I was able to see that `z3javascript` is failing to resolve at runtime

```
internal/modules/cjs/loader.js:982 Uncaught Error: Cannot find module 'z3javascript'
```

**Comment by jawline** [comment]
I think that the likely culprit is the build / install step I hacked together to compile a JavaScript compatible z3 on install  is not compatible with newer node versions but failed silently. If running an older version of node and reinstalling works then I'll try and fix this as a priority

**Comment by kumavis** [comment]
confirmed it works on node v8, ill PR an `"engines"` field to help make this clear
