### ISSUE TITLE
coerceToString, coerceToObject should be made consistent with ECMA standard

### ISSUE THREAD

**Issue by jawline** [ExpoSEJS/ExpoSE#47]
coerceToString should be rewritten to ToString,
coerceToObject should be rewritten ToObject,
etc for the informal model transformations

**Comment by tapaswenipathak** [comment]
Hi @jawline: Can I PR for the ticket? or is the ticket internal?

**Comment by jawline** [comment]
Feel free to take a look! in essence, I want to change coerceToObject, coerceToString, etc to ToBoolean, ToNumber, ToString and ToObject so that our function models can be more easily compared with the ECMA specification
