### ISSUE TITLE
How to use and get reports

### ISSUE THREAD

**Issue by jm4rc05** [ExpoSEJS/ExpoSE#75]
Hello,

I'm trying to learn and use some DSE tools, and found ExpoSE, but sorry, I couldn't get it to work. The question is: **what I'm doing wrong or not seeing properly?**

The setup was fine, and I executed successfully all tests running `./scripts/run_testes`.

Now I'm running the command `EXPOSE_LOG_LEVEL=3 EXPOSE_PRINT_PATHS=1 EXPOSE_PRINT_COVERAGE=1 expoSE ./minimist`, and after a few minutes I got some messages, evertything seens to be fine, but those two messages points to a dead-end:

```
[!] Wrote final coverage to /var/folders/g1/zw1lbf2x0gz_b1n899bhjszw0000gn/T/tmp-34291p8JnimJ4p6bm
[!] Wrote final output to /var/folders/g1/zw1lbf2x0gz_b1n899bhjszw0000gn/T/tmp-34291PpRL57fVU2JE
```

Those files doesn't exists after the script has finished! I got some more messages, a listing from `index.js`, and the files `index_jalangi.js` and `index_jalangi.json` was generated and I'm studying them now.

But I didn't got any luck running the UI! After selecting `minimist/index.js` using the *Analyze* option, runtime counter finish at ~18/19, no info is reported, and at Output tab I got:

```
( . . . )

,SyntaxError: Unexpected token in / in JSON at position 0
,at JSON.parse()
,at Object.(/Users/ra978165/Developer/ExpoSE/Distributor/bin/Distributor.js:39:23)
,at Module._compile(module.js:571:32)

( . . . )
```

The other tabs and all info is blank! At this point I ventured some debugging, and at this point ExpoSE seens to be trying to load `./minimist/index.js` using the `JSON.parser()` and I didn't figure out what can I do to fix my input, since the **Analyse** option didn't enable `.json` files! The **Load** option didn't the trick either!

A few hints would be greatly appreciated!

**Comment by jawline** [comment]
Hey,

Sorry about the late reply - I didn't notice the issue.

Do you want to execute an automatically generated test harness for minimist? If so I would try:
```
npm install minimist
RECOMPILE=1 EXPOSE_LOG_LEVEL=0 EXPOSE_PRINT_COVERAGE=1 expoSE ahg minimist
```

The ahg command will generate a generic harness for the program. If not then you will need to manually construct a test case (a small JS program which uses require to import the library, constructs some symbols and then calls the desired methods). Examples can be found in the tests/ folder.

Logging in ExpoSE is largely for development, and can actually break some programs, so for general analysis it should be turned off (console.log, toString, etc can have side-effects in the program under test).

**Comment by jm4rc05** [comment]
Great!!! I'll a spin. thanks
